### ISSUE TITLE
Fatal error on ine-line comment

### ISSUE THREAD

**Issue by Doodidan** [skovhus/SublimeLinter-contrib-sass-lint#24]
Linter throw fatal error when one-line comment is used.

Console command `sass-lint` no throw this error in the same time.

![image](https://user-images.githubusercontent.com/8870929/37650385-d1725b28-2c45-11e8-84d0-f703ff7c0642.png)
![image](https://user-images.githubusercontent.com/8870929/37650417-ef6bc722-2c45-11e8-8143-bec4039e85ea.png)
![image](https://user-images.githubusercontent.com/8870929/37650430-f8a4c096-2c45-11e8-820e-e7d8438b257b.png)

Used command for console:
```sass-lint -q -v sources/css/**/*.css --syntax scss```

**Comment by skovhus** [comment]
This doesn't seem like it is the `SublimeLinter-contrib-sass-lint` throwing this error. Seems you have another plugin `sass` returning this error. Can you try disabling other sass related plugins?

**Comment by LeaveAirykson** [comment]
i can confirm that issue. every comment outside a rule declaration throughs a validity error. No other sass related package is installed besides `sass` which is needed for syntax highlighting. I tried it with the `scss` instead of `sass` package but i get the same result.

Tested sass partial _test.scss:
```
// comment outside
.test-my-class {
    display: block;
    // comment inside
    color: #000;
}
```
Error output in Linter Console:
`1:1    error           sass: error        Please check validity of the block starting from line #1. (Fatal)`

CLI Command which is working:
`sass-lint -v -q _test.scss`

Other Linters used with `SublimeLinter` are working too. So i guess it must be `SublimeLinter-contrib-sass-lint` somehow?

**Edit**
I played around a little bit and found out it has to do with the call of `tmpfile` in `linter.py on line 96`. If you omit the `suffix` the sass errors are shown correctly again.

So If you change this:
`        return super(Sass, self).tmpfile(cmd, code,suffix)`
into this:
`        return super(Sass, self).tmpfile(cmd, code)`

everything works again. I'm new to python and the sublime package development, so i don't know if this is actually a fix or is it mandatory to pass the `suffix` variable?

**Edit 2**
Relates to PR #11 which also fixes the issue!

**Comment by skovhus** [comment]
Thanks for checking this. Seems we should merge that PR and get a new version out. : )

**Comment by LeaveAirykson** [comment]
Glad i could help! Thanks for building this Linter in the first place 😄 
The #11 PR should really fix the whole issue.

**Comment by skovhus** [comment]
1.2.0 is out, can you test if this solves the issue here?

@GoshaEgorian @LeaveAirykson

**Comment by LeaveAirykson** [comment]
Fix is working for sass and scss files 👍

**Comment by skovhus** [comment]
Thanks!
